### ISSUE TITLE
Validate new tests for Fisher and MannWhitney

### ISSUE THREAD

**Issue by jrossthomson** [jrossthomson/bigquery-utils#17]
Hi, I don't have time to get these new tests run. Can one of you two try to run the tests I have added here.

They got removed when the team went to the new JS version of testing.

Thanks!

**Comment by boaguilar** [comment]
Hi Ross, I am working on this, but seems they changed the way the functions are being tested.  Following their instruction, and after running "bash run_unit_test.sh" i get the following error: 

Step #4 - "copy_js_to_gcs": AccessDeniedException: 403 278857297430@cloudbuild.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object.

I will be working on this, and let you know if i make progress.
Boris
