### ISSUE TITLE
Error while testing kruskal_wallis udf

### ISSUE THREAD

**Issue by boaguilar** [jrossthomson/bigquery-utils#4]
While testing the code I got errors: 

AssertionError: Access Denied: BigQuery BigQuery: Error getting metadata for external code resource, please verify you have provided a valid path and/or that you have access to the resource: ${JS_BUCKET}/jstat-v1.9.4.min.js

I am wondering if I am missing a step in the testing process.

**Comment by jrossthomson** [comment]
Hey Boris I pulled your branch to a new branch which has Ian's latest additions: _add-boris_ I think if you follow the new instructions in contributing.md, you should be able to get the KW working. I think there are just some minor issues with SQL some of the UDFs you posted. I think the UI is a bit more liberal. Let me know if you want to get on a call to work on it together.

**Comment by boaguilar** [comment]
HI Ross, 
I got the pvalue test running without problems, so looks like the jStat library is working fine; but the kruskal_wallis function is still generating errors after I do  bash tests/run.sh -k community_kruskal_wallis

E   AssertionError: Function not found: `cgc-05-0042.fn_test_local_test.pvalue` at [35:27]

**Comment by jrossthomson** [comment]
Fixed as updating use of ENV variable.
